### ISSUE TITLE
"revisar entradas importadas" desde 8. E. Asignar

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#10]
No sé si es un error o tiene que ser así por algún motivo, pero si estás en la pestaña 8 y haces clic en el botón 'revisar entradas importadas', aunque haya avisos pendientes de revisar, no sale nada.

**Comment by Jordi59** [comment]
A nosotros sí que nos sale. Acabo de hacer la prueba (tanto en la pestaña "7.- Introducir" como en "8.- Asignar"): importo una entrada. Cambio de pestaña y vuelvo a la de "revisar entradas importadas" y me aparece.
