### ISSUE TITLE
¿Cambiar etiqueta de tabla?

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#11]
En las pestañas "asignar" y "Aceptar" la tabla que se presenta tiene una columna que se llama "asunto". Para el no iniciado parece que lo que tendría que aparecer ahí es el asunto de la entrada, pero lo que se presenta en realidad en esa columna es **asunto secretaría +[detalle]**.

Quizá se podría cambiar ese nombre de columna a algo parecido a **asunto scdl y detalle** o simplemente **asunto scdl**. De esta forma se puede relacionar mejor con lo que se va a presentar....

**Comment by Jordi59** [comment]
Quizás se puede cambiar por "Asunto [detalle]". Este campo es el que ven después todos.

**Comment by etchegaray** [comment]
De acuerdo con lo que dice Jordi. Con eso será suficiente...supongo

**Comment by etchegaray** [comment]
Revisado
