### ISSUE TITLE
Calendario de "¿El centro ha de contestar?" no se abre

### ISSUE THREAD

**Issue by Jordi59** [olvidio/tramity#12]
En un escrito: "¿El centro ha de contestar? -> Seleccionar "El día" -> al colocarse en el recuadro de la fecha no se abre el calendario. Hay que escribir la fecha "a mano". Debería aparecer el calendario como el los otros campos de "fecha"; por ejemplo "Fecha de escrito".
En principio este error ya lo dije, y entendí que se había arreglado. El caso es que no funciona ni con linux ni con windows.
No sé si puede haber un problema de diferentes navegadores, o versiones. Hace tiempo nos pasó (en concreto, me parece que con este calendario) que en windows no se abría.

**Comment by Jordi59** [comment]
Está arreglado en "9.- Aceptar", pero no en "1. Borrador (propio)" y "7. Acabados"
Está relacionado con el iusse #4

**Comment by olvidio** [comment]
Creo que faltaba actualizar...

**Comment by Jordi59** [comment]
Perfecto. Ya funciona correctamente.
