### ISSUE TITLE
Entrada con ref.  "desaparecido" en Tramity de centros, al marcar como visto.

### ISSUE THREAD

**Issue by Jordi59** [olvidio/tramity#18]
A Viaróoc han deixat de veure dlb 4955/23, al marcar el director com "visto", per donar-li entrada.
El mateix dia 2-IX els van arribar dos escrits. El director els va marcar “como visto”. Un sí que es pot veure (dlb 4976/23) i l’altre no (dlb 4955/23). Aquest segon ha desaparegut de tot arreu. No el tornen a trobar.
He entrat jo i, efectivament, no és en lloc (tampoc buscant). I va sortir bé i els va arribar.
Ho he dit també per correu electrònic.

**Comment by olvidio** [comment]
Parece que al entrar ha encontrado una ref y ha cambiado el asunto y detalle.

**Comment by Jordi59** [comment]
Cerramos la incidencia a la espera de si se repite en otros casos y encontrar la causa. No se ha visto ninguna vinculación con el asunto y detalle que había añadido (Plaza en crt de n. [Mossèn Francesc Perarnau]), y que no se correspondía con ninguna de las referencias: Montagut 2/22 (de 24/2/2022)
