### ISSUE TITLE
Etherpad: confusión en los comentarios

### ISSUE THREAD

**Issue by Jordi59** [olvidio/tramity#22]
No funciona bien el introducir comentarios en un etherpad después de la última actualización.
No guarda el autor del comentario, de manera que, cuando el documento sigue circulando, no se sabe quién lo ha hecho.
Tampoco funciona bien el añadir un texto alternativo en el comentario.
Seguramente tiene que ver con otra incidencia ya señalada de que no guarda ninguna preferencia de los usuarios del etherpad (color, idioma,...)

**Comment by olvidio** [comment]
cambios en settings.json del etherpad
