### ISSUE TITLE
Introducir E2 con contraseña

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#23]
Los E2 que envían desde los ctr, como la plantilla tiene contraseña, al intentar introducirlos dan un error. 
Fatal error: Uncaught Exception: Secured pdf file are currenttly not supported. in /var/www/tramity/vendor/smalot/PdfParser/Parser.php

¿Se podría solucionar este punto?.

**Comment by Jordi59** [comment]
De acuerdo con lo hablado, pienso que esta incidencia se puede cerrar. 
Los E2 no los procesa el Tramity. Los ponemos como "adjuntos" a un escrito etherpad con un texto del estilo "Se acompaña E2"
