### ISSUE TITLE
mensaje de error al poner mal usuario o contraseña

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#26]
Por seguridad, sería preferible que cuando se pone mal el usuario o la contraseña al logearse en el mensaje se dijera que el ususario o contraseña es erróneo.  Ahora mismo el mensaje te dice qué es erróneo (el usuario o la contraseña) con lo que da pistas del problema....

**Comment by olvidio** [comment]
Bueno.. piénsalo dos veces. Está así por que es un entorno cerrado y te
ahorra tiempo: todo el que estas al teléfono atendiendo a alguien que no le
va la contraseña hasta que descubre que no tiene bien el usuario... Antes
lo tenía como dices. No me cuesta nada cambiarlo, y aquí ya se han
acostumbrado: me refiero a que las quejas de passwords son al principio.

Missatge de etchegaray ***@***.***> del dia dj., 16 de nov.
2023 a les 15:46:

**Comment by etchegaray** [comment]
Déjalo por ahora como está. Es algo que me ha dicho Eduardo y he preferido
escribirlo para que no se me olvide...
