### ISSUE TITLE
Salida mal formateada.

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#47]
Adjunto archivo .html, archivo .md (mark down) y pdf resultante. Como se verá, algo no lo entiende bien y el anexo no sale correcto, se come algunas lineas. Los archivos .md y html les he añadido la extensión .txt porque github no permite subir ese tipo de archivos.

No sé si es por mal uso de las listas automáticas o por algún otro tipo de marca introducida. 

Por si sirve...
[dlp_3222_24.pdf](https://github.com/olvidio/tramity/files/14638831/dlp_3222_24.pdf)
[g.sfkTrUoTnq6oZTb5$dlp esc1030539.html.txt](https://github.com/olvidio/tramity/files/14638869/g.sfkTrUoTnq6oZTb5.dlp.esc1030539.html.txt)
[g.sfkTrUoTnq6oZTb5$dlp esc1030539.md.txt](https://github.com/olvidio/tramity/files/14638870/g.sfkTrUoTnq6oZTb5.dlp.esc1030539.md.txt)

**Comment by olvidio** [comment]
ok. se puede hacer git pull

Missatge de etchegaray ***@***.***> del dia dl., 18 de març
2024 a les 16:50:

**Comment by etchegaray** [comment]
Solucionado
