### ISSUE TITLE
visibilidad por defecto

### ISSUE THREAD

**Issue by etchegaray** [olvidio/tramity#9]
Pienso que la visibilidad por defecto tanto al crear un nuevo escrito como al gestionar una entrada, si no hay datos de referencia que indiquen otra cosa, debería ser **personal** Ahora mismo está como **todos** y puede ser un problema si no se está atento....

**Comment by Jordi59** [comment]
Me parece bien

**Comment by Jordi59** [comment]
Se trataría de cambiar también en las entradas (en los escritos que se generan ya es así, me parece)

**Comment by olvidio** [comment]
Comprobar y cerrar.
En los escritos por defecto se hereda la visibilidad del expediente.
